name: 'Composite Action'
description: 'A composite action to set up Node.js and install dependencies'

inputs:
  node-version:
    description: 'Node version to be used'
    required: false
    default: '22'

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci