name: Solar System Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "feature/*"
env:
  MONGO_URI: "mongodb+srv://supercluster.d83jj.mongodb.net/superData"
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  unit-tests:
    name: Run Unit Tests
    # strategy:
    #   matrix:
    #     node-version: [20, 18, 19]
    #     os: [ubuntu-latest, windows-latest]
    #     exclude:
    #       - node-version: 19
    #         os: windows-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 20

      - name: Cache node modules
        uses: actions/cache@v6
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Archive test results
        # if:: steps.unit-tests.outcome == 'failure' || steps.unit-tests.outcome == 'success'
        # Just an example of how to use the `if` condition to always run this step regardless of the previous step's outcome usinf step context.
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-results ${{github.actor}}
          path: test-results.xml
          retention-days: 1

  Code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 20

      - name: Cache node modules
        uses: actions/cache@v6
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Run code coverage
        continue-on-error: true
        run: npm run coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report ${{github.actor}}
          path: coverage
          retention-days: 1

  Docker:
    name: Build and Push Docker Image
    needs: [unit-tests, Code-coverage]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/solar-system:${{ github.sha }}