name: Solar System Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "feature/*"
env:
  MONGO_URI: "mongodb+srv://supercluster.d83jj.mongodb.net/superData"
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  unit-tests:
    name: Run Unit Tests
    # strategy:
    #   matrix:
    #     node-version: [20, 18, 19]
    #     os: [ubuntu-latest, windows-latest]
    #     exclude:
    #       - node-version: 19
    #         os: windows-latest
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4

      # - name: setup Node.js
      #   uses: actions/setup-node@v7
      #   with:
      #     node-version: 24

      # - name: Cache node modules
      #   uses: actions/cache@v6
      #   with:
      #     path: node_modules
      #     key: {{ runner.os }}-node-{{ hashFiles('package-lock.json') }}

      # - name: Install dependencies
      #   run: npm install
      - name: Using Composite actions
        uses: ./.github/actions/action.yaml
        with:
          node-version: '20'

      - name: Run unit tests
        run: npm test

      - name: Archive test results
        # if:: steps.unit-tests.outcome == 'failure' || steps.unit-tests.outcome == 'success'
        # Just an example of how to use the `if` condition to always run this step regardless of the previous step's outcome usinf step context.
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-results ${{github.actor}}
          path: test-results.xml
          retention-days: 1

  Code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 20

      - name: Cache node modules
        uses: actions/cache@v6
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Run code coverage
        continue-on-error: true
        run: npm run coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report ${{github.actor}}
          path: coverage
          retention-days: 1

  Container-build:
    name: Build and Push Docker Image
    needs: [unit-tests, Code-coverage]
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GHCR Hub
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Docker image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ secrets.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker image
        run: |
          docker run -d \
            --name solar-system-app \
            --publish 3000:3000 \
            -e MONGO_URI="${{ env.MONGO_URI }}" \
            -e MONGO_USERNAME="${{ vars.MONGO_USERNAME }}" \
            -e MONGO_PASSWORD="${{ secrets.MONGO_PASSWORD }}" \
            ${{ secrets.DOCKER_USERNAME }}/solar-system:${{ github.sha }}

          echo "Waiting for service to start..."
          sleep 5

          echo Testing Image URL using wget
          wget -qO- 127.0.0.1:3000/live | grep live
            
      - name: Push Docker image to Docker Hub and GHCR
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/solar-system:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}
          
  Dev-Deployment:
    name: Deploy to Development Environment
    if: github.ref != 'refs/heads/main'
    needs: Container-build
    environment:
      name: deployment
      url: http://${{ steps.set-app-ingress-url.outputs.APP_INGRESS_HOST }}
    outputs:
      APP_INGRESS_HOST: ${{ steps.set-app-ingress-url.outputs.APP_INGRESS_HOST }}
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Fetch ingress controller ip address
        run: |
          echo "INGRESS_IP=$(kubectl get svc -n ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_ENV
          
      - name: Fetch K8's Cluster details
        run: |
          kubectl version --client
          echo -------------------
          kubectl get nodes

      - name: Replace tokens in deployment.yaml
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '_{_'
          tokenSuffix: '_}_'
          files: '["kubernetes/deployment.yaml"]'
        env:
            ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"
            NAMESPACE: ${{ vars.NAMESPACE }}
            REPLICAS: ${{ vars.REPLICAS }}
            IMAGE: ${{ secrets.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
            INGRESS_IP: ${{ env.INGRESS_IP }}

      - name: Read Deployment yaml file
        run: |
          cat kubernetes/deployment.yaml

      - name: Apply Deployment to K8s Cluster
        run: |  
          kubectl apply -f kubernetes/deployment.yaml
          echo "Waiting for deployment to be ready..."
          kubectl rollout status deployment/solar-system-deployment -n ${{ vars.NAMESPACE }} --timeout=120s

      - name: Set app ingress URL
        id: set-app-ingress-url
        run: |
          echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ingress -o jsonpath='{.items[0].spec.rules[0].host[0]}')" >> $GITHUB_OUTPUT

  Integration-tests-Dev:
    name: Run Integration Tests
    needs: Dev-Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Test Integration using wget
        env: 
          url: http://${{ needs.Dev-Deployment.outputs.APP_INGRESS_HOST }}/live
        run: |
          echo $url
          echo "_____________________________________"
          curl -s -k http://${{ needs.Dev-Deployment.outputs.APP_INGRESS_HOST }}/live | grep -i live
          
  Prod-Deployment:
    name: Deploy to Production Environment
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: Container-build
    environment:
      name: prod
      url: http://${{ steps.set-app-ingress-url.outputs.APP_INGRESS_HOST }}
    outputs:
      APP_INGRESS_HOST: ${{ steps.set-app-ingress-url.outputs.APP_INGRESS_HOST }}
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Fetch ingress controller ip address
        run: |
          echo "INGRESS_IP=$(kubectl get svc -n ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_ENV
          
      - name: Fetch K8's Cluster details
        run: |
          kubectl version --client
          echo -------------------
          kubectl get nodes

      - name: Replace tokens in production.yaml
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '_{_'
          tokenSuffix: '_}_'
          files: '["kubernetes/production.yaml"]'
        env:
            ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"
            NAMESPACE: ${{ vars.NAMESPACE }}
            REPLICAS: ${{ vars.REPLICAS }}
            IMAGE: ${{ secrets.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
            INGRESS_IP: ${{ env.INGRESS_IP }}

      - name: Read Production yaml file
        run: |
          cat kubernetes/production.yaml

      - name: Apply Production Configuration to K8s Cluster
        run: |  
          kubectl apply -f kubernetes/production.yaml
          

      - name: Set app ingress URL
        id: set-app-ingress-url
        run: |
          echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ingress -o jsonpath='{.items[0].spec.rules[0].host[0]}')" >> $GITHUB_OUTPUT

  Integration-tests-Prod:
    name: Run Integration Tests
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: Prod-Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Test Integration using wget
        env: 
          url: http://${{ needs.Prod-Deployment.outputs.APP_INGRESS_HOST }}/live
        run: |
          echo $url
          echo "_____________________________________"
          curl -s -k http://${{ needs.Prod-Deployment.outputs.APP_INGRESS_HOST }}/live | grep -i live        
  
          